title: JekyllChess
description: A theme for chess blogging with figurine notation, FEN diagrams, and a simple PGN viewer. Built on chess.js and chessboard.js libraries.
url: "https://jekyllrookpawn.github.io"
exclude:
- README.md
